export const GET_INCOME = "GET_INCOME";
export const GET_INCOME_BY_NAME = "GET_INCOME_BY_NAME";
export const CREATE_INCOME = "CREATE_INCOME";
export const UPDATE_INCOME_BY_ID = "UPDATE_INCOME_BY_ID";
export const DELETE_INCOME_BY_ID = "DELETE_INCOME_BY_ID";
